# Air Configuration for tmiDB API Component
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/tmidb-api"
cmd = "go build -o ./tmp/tmidb-api ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "views", "data", "logs", ".git"]
exclude_file = []
exclude_regex = ["_test.go", ".*_test\\.go$"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["."]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "2s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_root = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
